## USB port
port: /dev/imu


##### Calibration ####
### accelerometer
#accel_x_min: -250.0
#accel_x_max: 250.0
#accel_y_min: -250.0
#accel_y_max: 250.0
#accel_z_min: -250.0
#accel_z_max: 250.0

### Calibration Values ###
accel_x_min: -264.0
accel_x_max: 254.09
accel_y_min: -258.0
accel_y_max: 266.0
accel_z_min: -274.0
accel_z_max: 233.0

### magnetometer
# standard calibration
magn_x_min: -600.0
magn_x_max: 600.0
magn_y_min: -600.0
magn_y_max: 600.0
magn_z_min: -600.0
magn_z_max: 600.0

# extended calibration
calibration_magn_use_extended: true
magn_ellipsoid_center: [98.9334, 37.0545, -3.94387]
magn_ellipsoid_transform: [[0.978729, -0.0121544, -0.00598809], [-0.0121544, 0.991767, -0.000778958], [-0.00598809, -0.000778958, 0.992890]]

# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
### Calibration Values ###
gyro_average_offset_x: -65.22
gyro_average_offset_y: -11.42
gyro_average_offset_z: 4.79

#gyro_average_offset_x: 0.0
#gyro_average_offset_y: 0.0
#gyro_average_offset_z: 0.0
